services:
  shorty-web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    env_file:
      - .env
    ports:
      - '3010:3000'

  shorty-redirect:
    build:
      context: .
      dockerfile: ./apps/redirect/Dockerfile
    env_file:
      - .env
    ports:
      - '3011:3000'
