import avatar_artyom from '@/public/avatar_artyom.jpg'
import { LinkRecordType } from '@/shared/types/link-record-type'

const linkData: LinkRecordType[] = [
  {
    uid: '1',
    title: 'Youtube Channelfrfrfr',
    url: 'https://www.youtube.com/c/Ap73MKa',
    createDate: new Date(),
    tag: 'Youtube',
    imageURL: avatar_artyom.src,
  },
  {
    uid: '2',
    title: 'VK',
    url: 'https://www.vk.com',
    createDate: new Date(),
    tag: 'Youtube',
    imageURL: '',
  },
  {
    uid: '3',
    title: 'Elixor',
    url: 'https://www.elixor.com',
    createDate: new Date(),
    tag: 'Vk',
    imageURL: '',
  },
  {
    uid: '4',
    title: 'Elixor',
    url: 'https://www.elixor.com',
    createDate: new Date(),
    tag: 'Vk',
    imageURL: '',
  },
  {
    uid: '5',
    title: 'Elixor',
    url: 'https://www.elixor.com',
    createDate: new Date(),
    tag: 'Vk',
    imageURL: '',
  },
  {
    uid: '6',
    title: 'Elixor',
    url: 'https://www.elixor.com',
    createDate: new Date(),
    tag: 'Vk',
    imageURL: '',
  },
  {
    uid: '7',
    title: 'Elixor',
    url: 'https://www.elixor.com',
    createDate: new Date(),
    tag: 'Vk',
    imageURL: '',
  },
  {
    uid: '8',
    title: 'Elixor',
    url: 'https://www.elixor.com',
    createDate: new Date(),
    tag: 'Vk',
    imageURL: '',
  },
  {
    uid: '9',
    title: 'Elixor',
    url: 'https://www.elixor.com',
    createDate: new Date(),
    tag: 'Vk',
    imageURL: '',
  },
  {
    uid: '10',
    title: 'Elixor',
    url: 'https://www.elixor.com',
    createDate: new Date(),
    tag: 'Vk',
    imageURL: '',
  },
  {
    uid: '11',
    title: 'Elixor',
    url: 'https://www.elixor.com',
    createDate: new Date(),
    tag: 'Vk',
    imageURL: '',
  },
]

export default linkData
